export type AppealDecisionRecord = {
  year?: string;
  appealNumber?: string;
  permitNumber?: string;
  address?: string;
  propertyType?: string;
  propertyUse?: string;
  originalDecision?: string;
  appealFiledDate?: string;
  initialMeetingDate?: string;
  finalSessionDate?: string;
  decisionIssuedDate?: string;
  appealDecision?: string;
};

export type Permit = {
  permitnum?: string;
  address?: string;
  applicant?: string;
  category?: string;
  description?: string;
  proposedusecode?: string;
  proposedusedescription?: string;
  permitteddiscretionary?: string;
  landusedistrict?: string;
  landusedistrictdescription?: string;
  statuscurrent?: string;
  applieddate?: string;
  decisiondate?: string;
  releasedate?: string;
  mustcommencedate?: string;
  canceledrefuseddate?: string;
  decision?: string;
  decisionby?: string;
  sdabnumber?: string;
  sdabhearingdate?: string;
  sdabdecision?: string;
  sdabdecisiondate?: string;
  appealreporturl?: string;
  appealdecisionrecord?: AppealDecisionRecord;
  communityname?: string;
  ward?: string;
  latitude?: string;
  longitude?: string;
};
